#!/usr/bin/env bash
set -euxo pipefail
files=$(git diff --cached --name-only --diff-filter ACM | grep '\.go$' || true)
dirs=$(for f in $files ; do dirname $f; done | sort | uniq)
for d in $dirs ; do
	( cd $d ; errcheck -abspath -ignoretests=false )
done
for f in $files ; do
	goimports -w $f
	git add $f
done
staticcheck ./...
go vet ./...
go test -race ./...
# Did I forget copying the latest version of the hook?
cmp pre-commit $0
